name: GitHub Run&Build Action
description: This action runs a `build.sh` script to build a site and deploys against GHpages

branding:
  icon: 'home'
  color: 'red'

runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  GH_PAGES_BRANCH:
    description: 'override the default `gh-pages` deployment branch'
    required: false
    default: 'gh-pages'

  SOURCE_FOLDER:
    description: 'override the default `content` folder for sources for website'
    required: false
    default: 'content'

  DONOTPUBLISH:
    description: 'Set to any value to stop job before pushing to GH-Pages'
    required: false
    default: ''
